### ISSUE TITLE
Pathfinder interface as a program

### ISSUE THREAD

**Issue by llunaCreixent** [chriseth/pathfinder#2]
I want to use the pathfinder as a program. The following command works perfectly with an old version of the binary.
```
./pathfinder_old  0x19ED34ea99E02be39B9B78003b504564C43DAE79 0xC1a9Cd654956Dc44FB50Ba388b56057312fF4621 1000000000000000000 edges.json
```
With the `edges.json` file containing:
```
[{"from":"0x19ED34ea99E02be39B9B78003b504564C43DAE79","to":"0xC1a9Cd654956Dc44FB50Ba388b56057312fF4621","token":"0x19ED34ea99E02be39B9B78003b504564C43DAE79","capacity":"7499899999999966265"}]
```
Returns:
```
{"maxFlowValue":"1000000000000000000","transferSteps":[{"from":"0x19ED34ea99E02be39B9B78003b504564C43DAE79","step":0,"to":"0xC1a9Cd654956Dc44FB50Ba388b56057312fF4621","token":"0x19ED34ea99E02be39B9B78003b504564C43DAE79","value":"1000000000000000000"}]}
```
How should the query be formed to get a valid result using the last version of the pathfinder? Now the execution returns:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
Thanks!

**Comment by chriseth** [comment]
The new binary is built to compute the edges from a safe/trust graph export itself. The way the edges are computed is different and it can find some paths that the old binary would not have been able to produce. I can either re-add the old way to import the `edgs.json`, or you update to use the new way - both is fine with me. There is also a way to run the pathfinder such that it always keeps up to date with changes in the graph. You can take a look at `webservice.js` about how to use the `pathfinderd` module.

**Comment by llunaCreixent** [comment]
Cool improvements! It'd be nice to have available the old way to import the `edges.json`, while we plan the update. Thanks!

**Comment by llunaCreixent** [comment]
Because what we want is to just use the maxflow function.

**Comment by chriseth** [comment]
I'm actually wondering if updating brings you any benefit at all, since I'm not sure if there were any changes at all in the pathfinder after the edges have been computed - let me check.

**Comment by llunaCreixent** [comment]
Thanks @chriseth! Have you checked the updates? We thought that the the algorithm that calculates the transfer steps based on the calculated capacities was updated. If that's not the case and the updates only affect  the indexing and calculation of the capacities, therefore we won't obtain different results by updating the pathfinder. Thus, the reason of the difference between the transfer steps result from [your last version](https://chriseth.github.io/pathfinder/) and [the circles.graden api](https://api.circles.garden/api/transfers) is that the indexing algorithmms are different and the capacities db holds different values.

**Comment by llunaCreixent** [comment]
Thank you @chriseth !! It works now with your updates :)
